name: flutter_baidu_map_example
description: Demonstrates how to use the flutter_baidu_map plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  permission_handler: ^5.0.0+hotfix.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_baidu_map:
    path: ../

flutter:
  uses-material-design: true
