name: flutter_baidu_map
description: flutter 百度地图定位组件.
version: 0.0.6

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    androidPackage: com.mld.flutter_baidu_map
    pluginClass: FlutterBaiduMapPlugin
